
---
- name: Configure elk with filebeat
  hosts: webservers
  remote_user: sysadmin
  become: true
  tasks:

  - name: Download filebeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/f>

  - name: Install filebeat
    command: sudo dpkg -i filebeat-7.6.1-amd64.deb

  - name: Copy filebeat config files
    ansible.builtin.copy:
      src: /etc/ansible/Files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable filebeat modules
                               [ Read 57 lines ]

