---
- name: Configure elk vm with Docker
  hosts: elk
  remote_user: sysadmin
  become: true
  tasks:

  - name: Install docker.io
    apt:
      update_cache: yes
      force_apt_get: yes
      name: docker.io
      state: present

  - name: Install python3-pip
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

